### ISSUE TITLE
New VRChat SDK Update

### ISSUE THREAD

**Issue by MolotovCherry** [GotoFinal/GotoUdon#16]
Doesn't seem to be compatible with the latest one. 2020.06.16.20.53

**Comment by GotoFinal** [comment]
Client manager got fixed in 1.3.0 in https://github.com/GotoFinal/GotoUdon/pull/17 but for emulator you will need to wait a bit longer. But client manager support now testing locally, so you no longer need to upload worlds to vrchat servers just to test them.

**Comment by GotoFinal** [comment]
@cherryleafroad fixed
